### PR TITLE
Prepublication edits for PCC.mAPS public comment version

### PR DESCRIPTION
**Pull request by MaryLJ**
Closes # 

## 📑 Description

Prepublication edits for PCC.mAPS public comment version

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed
- [x] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@MaryLJ download.md is missing. Did you intend to remove it? or fail to add it?

**Comment by MaryLJ** [comment]
It should be there now, thanks.

**Comment by JohnMoehrke** [comment]
FYI: Here is the CI build
https://build.fhir.org/ig/IHE/PCC.mAPS/branches/mlj_prepub_edits_mAPS_rev_1-0-0-comment_may2024/qa.html

**Review by JohnMoehrke — COMMENTED** [review]
I fixed a bunch of link errors.

**Pull request merged**
